// starters/react-cineapp/src/App.jsx
import { useState } from 'react'
import Header from './components/Header'
import MovieCard from './components/MovieCard'
import { mockMovies } from './mockData'
import './App.css'

function App() {
  const [movies] = useState(mockMovies);

  return (
    <div className="app">
      <Header />
      <main>
        <div className="movie-grid">
          {movies.map(movie => (
            <MovieCard key={movie.id} movie={movie} />
          ))}
        </div>
      </main>
    </div>
  )
}

export default App

// starters/vue-cineapp/src/App.vue
<template>
  <div class="app">
    <Header />
    <main>
      <div class="movie-grid">
        <MovieCard v-for="movie in movies" :key="movie.id" :movie="movie" />
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Header from './components/Header.vue';
import MovieCard from './components/MovieCard.vue';
import { mockMovies } from './mockData';
import './App.css';

const movies = ref(mockMovies);
</script>
