// starters/vue-cineapp/src/components/MovieCard.vue
<template>
  <div class="movie-card">
    <img :src="imageUrl" :alt="movie.title" />
    <h3>{{ movie.title }}</h3>
    <p>⭐ {{ movie.vote_average }}</p>
    <!-- TODO : Bouton de favoris ❤️ -->
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps(['movie']);

const imageUrl = computed(() => `https://image.tmdb.org/t/p/w500${props.movie.poster_path}`);
</script>

// starters/react-cineapp/src/components/MovieCard.jsx
export default function MovieCard({ movie }) {
  const imageUrl = `https://image.tmdb.org/t/p/w500${movie.poster_path}`;

  return (
    <div className="movie-card">
      <img src={imageUrl} alt={movie.title} />
      <h3>{movie.title}</h3>
      <p>⭐ {movie.vote_average}</p>
      {/* TODO : Bouton de favoris ❤️ */}
    </div>
  );
}
